build: off

image:
    - Visual Studio 2015
    - Ubuntu

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
  - TARGET: i686-pc-windows-gnu
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - cmd: rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - cmd: SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - cmd: SET PATH=%PATH%;C:\MinGW\bin
  - sh: curl https://sh.rustup.rs -sSf | sh
  - rustc -V
  - cargo -V

build_script:
  - cargo build --verbose

test_script:
  - cargo test --verbose
